### ISSUE TITLE
Functional "setup" command line argument

### ISSUE THREAD

**Issue by JR-Mitchell** [JR-Mitchell/DriveFinance#3]
The "setup" argument should correctly set up the program

**Comment by OneSlightWeirdo** [comment]
As of 3b64a2242a94f5b93f654c0472d29ac958b10859, report autocreation implemented.

**Comment by OneSlightWeirdo** [comment]
As of 4b3992778085903d74ce43c0251572bd25b2d1e6, drive files and folders are autogenerated (initially intended to be part of `--setup` process but now moved into `DriveFolder` initialisation). Final thing before closing: setting up payment shortcuts.

**Comment by JR-Mitchell** [comment]
As of 19a398c1ad83c7b11a17ac8e17c2466eb8f6cf2c adding payment shortcuts in --setup works. Closing this issue
